# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Dict, List, Union, Optional
from datetime import datetime
from typing_extensions import Literal, TypeAlias

from pydantic import Field as FieldInfo

from .._models import BaseModel

__all__ = [
    "MonitorUpdateResponse",
    "MonitorsPageExactMonitor",
    "MonitorsPageExactMonitorChangeDetection",
    "MonitorsPageExactMonitorSchedule",
    "MonitorsPageExactMonitorTarget",
    "MonitorsPageExactMonitorWebhook",
    "MonitorsSitemapExactMonitor",
    "MonitorsSitemapExactMonitorChangeDetection",
    "MonitorsSitemapExactMonitorSchedule",
    "MonitorsSitemapExactMonitorTarget",
    "MonitorsSitemapExactMonitorWebhook",
    "MonitorsPageSemanticMonitor",
    "MonitorsPageSemanticMonitorChangeDetection",
    "MonitorsPageSemanticMonitorSchedule",
    "MonitorsPageSemanticMonitorTarget",
    "MonitorsPageSemanticMonitorWebhook",
    "MonitorsExtractSemanticMonitor",
    "MonitorsExtractSemanticMonitorChangeDetection",
    "MonitorsExtractSemanticMonitorSchedule",
    "MonitorsExtractSemanticMonitorTarget",
    "MonitorsExtractSemanticMonitorWebhook",
]


class MonitorsPageExactMonitorChangeDetection(BaseModel):
    """Detect exact changes.

    For page targets, this means visible text diffs. For sitemap targets, this means URL additions and removals.
    """

    type: Literal["exact"]


class MonitorsPageExactMonitorSchedule(BaseModel):
    """Run the monitor on a fixed interval defined by a frequency and a unit, e.g.

    every 6 hours or every 2 days. The total interval (frequency × unit) must be between 10 minutes and 1 year.
    """

    frequency: int
    """Number of units between runs.

    The resulting interval (frequency × unit) must be at least 10 minutes and at
    most 1 year (e.g. minimum 10 when unit is minutes; maximum 365 when unit is
    days).
    """

    type: Literal["interval"]

    unit: Literal["minutes", "hours", "days"]


class MonitorsPageExactMonitorTarget(BaseModel):
    type: Literal["page"]

    url: str

    normalize_whitespace: Optional[bool] = None
    """Normalize whitespace before comparing or analyzing text."""


class MonitorsPageExactMonitorWebhook(BaseModel):
    url: str
    """Webhook URL called when a change is detected."""

    secret: Optional[str] = None
    """Signing secret used to verify webhook authenticity.

    Each delivery includes an `X-Context-Signature: t=<unix>,v1=<hmac>` header,
    where the HMAC is SHA-256 over `"{t}.{rawRequestBody}"` keyed by this secret.
    Recompute it with a constant-time compare and reject stale timestamps to prevent
    replay. Generated by the API; cannot be set by clients.
    """


class MonitorsPageExactMonitor(BaseModel):
    """A page monitor using exact change detection."""

    id: str

    change_detection: MonitorsPageExactMonitorChangeDetection
    """Detect exact changes.

    For page targets, this means visible text diffs. For sitemap targets, this means
    URL additions and removals.
    """

    created_at: datetime

    name: str

    schedule: MonitorsPageExactMonitorSchedule
    """Run the monitor on a fixed interval defined by a frequency and a unit, e.g.

    every 6 hours or every 2 days. The total interval (frequency × unit) must be
    between 10 minutes and 1 year.
    """

    status: Literal["active", "paused", "failed"]

    target: MonitorsPageExactMonitorTarget

    updated_at: datetime

    last_change_at: Optional[datetime] = None

    last_run_at: Optional[datetime] = None

    tags: Optional[List[str]] = None
    """User-defined tags for grouping and filtering monitors and their changes."""

    webhook: Optional[MonitorsPageExactMonitorWebhook] = None


class MonitorsSitemapExactMonitorChangeDetection(BaseModel):
    """Detect exact changes.

    For page targets, this means visible text diffs. For sitemap targets, this means URL additions and removals.
    """

    type: Literal["exact"]


class MonitorsSitemapExactMonitorSchedule(BaseModel):
    """Run the monitor on a fixed interval defined by a frequency and a unit, e.g.

    every 6 hours or every 2 days. The total interval (frequency × unit) must be between 10 minutes and 1 year.
    """

    frequency: int
    """Number of units between runs.

    The resulting interval (frequency × unit) must be at least 10 minutes and at
    most 1 year (e.g. minimum 10 when unit is minutes; maximum 365 when unit is
    days).
    """

    type: Literal["interval"]

    unit: Literal["minutes", "hours", "days"]


class MonitorsSitemapExactMonitorTarget(BaseModel):
    type: Literal["sitemap"]

    url: str
    """Sitemap URL to monitor."""

    exclude: Optional[List[str]] = None
    """URL path patterns to exclude."""

    include: Optional[List[str]] = None
    """URL path patterns to include."""

    max_urls: Optional[int] = None


class MonitorsSitemapExactMonitorWebhook(BaseModel):
    url: str
    """Webhook URL called when a change is detected."""

    secret: Optional[str] = None
    """Signing secret used to verify webhook authenticity.

    Each delivery includes an `X-Context-Signature: t=<unix>,v1=<hmac>` header,
    where the HMAC is SHA-256 over `"{t}.{rawRequestBody}"` keyed by this secret.
    Recompute it with a constant-time compare and reject stale timestamps to prevent
    replay. Generated by the API; cannot be set by clients.
    """


class MonitorsSitemapExactMonitor(BaseModel):
    """A sitemap monitor using exact change detection."""

    id: str

    change_detection: MonitorsSitemapExactMonitorChangeDetection
    """Detect exact changes.

    For page targets, this means visible text diffs. For sitemap targets, this means
    URL additions and removals.
    """

    created_at: datetime

    name: str

    schedule: MonitorsSitemapExactMonitorSchedule
    """Run the monitor on a fixed interval defined by a frequency and a unit, e.g.

    every 6 hours or every 2 days. The total interval (frequency × unit) must be
    between 10 minutes and 1 year.
    """

    status: Literal["active", "paused", "failed"]

    target: MonitorsSitemapExactMonitorTarget

    updated_at: datetime

    last_change_at: Optional[datetime] = None

    last_run_at: Optional[datetime] = None

    tags: Optional[List[str]] = None
    """User-defined tags for grouping and filtering monitors and their changes."""

    webhook: Optional[MonitorsSitemapExactMonitorWebhook] = None


class MonitorsPageSemanticMonitorChangeDetection(BaseModel):
    """Detect meaning-level changes that match a natural language query."""

    query: str

    type: Literal["semantic"]

    confidence_threshold: Optional[float] = None


class MonitorsPageSemanticMonitorSchedule(BaseModel):
    """Run the monitor on a fixed interval defined by a frequency and a unit, e.g.

    every 6 hours or every 2 days. The total interval (frequency × unit) must be between 10 minutes and 1 year.
    """

    frequency: int
    """Number of units between runs.

    The resulting interval (frequency × unit) must be at least 10 minutes and at
    most 1 year (e.g. minimum 10 when unit is minutes; maximum 365 when unit is
    days).
    """

    type: Literal["interval"]

    unit: Literal["minutes", "hours", "days"]


class MonitorsPageSemanticMonitorTarget(BaseModel):
    type: Literal["page"]

    url: str

    normalize_whitespace: Optional[bool] = None
    """Normalize whitespace before comparing or analyzing text."""


class MonitorsPageSemanticMonitorWebhook(BaseModel):
    url: str
    """Webhook URL called when a change is detected."""

    secret: Optional[str] = None
    """Signing secret used to verify webhook authenticity.

    Each delivery includes an `X-Context-Signature: t=<unix>,v1=<hmac>` header,
    where the HMAC is SHA-256 over `"{t}.{rawRequestBody}"` keyed by this secret.
    Recompute it with a constant-time compare and reject stale timestamps to prevent
    replay. Generated by the API; cannot be set by clients.
    """


class MonitorsPageSemanticMonitor(BaseModel):
    """A page monitor using semantic change detection."""

    id: str

    change_detection: MonitorsPageSemanticMonitorChangeDetection
    """Detect meaning-level changes that match a natural language query."""

    created_at: datetime

    name: str

    schedule: MonitorsPageSemanticMonitorSchedule
    """Run the monitor on a fixed interval defined by a frequency and a unit, e.g.

    every 6 hours or every 2 days. The total interval (frequency × unit) must be
    between 10 minutes and 1 year.
    """

    status: Literal["active", "paused", "failed"]

    target: MonitorsPageSemanticMonitorTarget

    updated_at: datetime

    last_change_at: Optional[datetime] = None

    last_run_at: Optional[datetime] = None

    tags: Optional[List[str]] = None
    """User-defined tags for grouping and filtering monitors and their changes."""

    webhook: Optional[MonitorsPageSemanticMonitorWebhook] = None


class MonitorsExtractSemanticMonitorChangeDetection(BaseModel):
    """Detect meaning-level changes that match a natural language query."""

    query: str

    type: Literal["semantic"]

    confidence_threshold: Optional[float] = None


class MonitorsExtractSemanticMonitorSchedule(BaseModel):
    """Run the monitor on a fixed interval defined by a frequency and a unit, e.g.

    every 6 hours or every 2 days. The total interval (frequency × unit) must be between 10 minutes and 1 year.
    """

    frequency: int
    """Number of units between runs.

    The resulting interval (frequency × unit) must be at least 10 minutes and at
    most 1 year (e.g. minimum 10 when unit is minutes; maximum 365 when unit is
    days).
    """

    type: Literal["interval"]

    unit: Literal["minutes", "hours", "days"]


class MonitorsExtractSemanticMonitorTarget(BaseModel):
    type: Literal["extract"]

    url: str
    """Root URL to extract structured data from."""

    follow_subdomains: Optional[bool] = None

    instructions: Optional[str] = None
    """Optional natural-language instructions guiding what to extract."""

    max_depth: Optional[int] = None
    """Optional maximum link depth from the starting URL (0 = only the starting page)."""

    max_pages: Optional[int] = None
    """Maximum number of pages to analyze during extraction."""

    schema_: Optional[Dict[str, object]] = FieldInfo(alias="schema", default=None)
    """JSON Schema describing the structured data to extract and watch for changes.

    If omitted, a default summary + key-points schema is used.
    """


class MonitorsExtractSemanticMonitorWebhook(BaseModel):
    url: str
    """Webhook URL called when a change is detected."""

    secret: Optional[str] = None
    """Signing secret used to verify webhook authenticity.

    Each delivery includes an `X-Context-Signature: t=<unix>,v1=<hmac>` header,
    where the HMAC is SHA-256 over `"{t}.{rawRequestBody}"` keyed by this secret.
    Recompute it with a constant-time compare and reject stale timestamps to prevent
    replay. Generated by the API; cannot be set by clients.
    """


class MonitorsExtractSemanticMonitor(BaseModel):
    """An extract monitor using semantic change detection."""

    id: str

    change_detection: MonitorsExtractSemanticMonitorChangeDetection
    """Detect meaning-level changes that match a natural language query."""

    created_at: datetime

    name: str

    schedule: MonitorsExtractSemanticMonitorSchedule
    """Run the monitor on a fixed interval defined by a frequency and a unit, e.g.

    every 6 hours or every 2 days. The total interval (frequency × unit) must be
    between 10 minutes and 1 year.
    """

    status: Literal["active", "paused", "failed"]

    target: MonitorsExtractSemanticMonitorTarget

    updated_at: datetime

    last_change_at: Optional[datetime] = None

    last_run_at: Optional[datetime] = None

    tags: Optional[List[str]] = None
    """User-defined tags for grouping and filtering monitors and their changes."""

    webhook: Optional[MonitorsExtractSemanticMonitorWebhook] = None


MonitorUpdateResponse: TypeAlias = Union[
    MonitorsPageExactMonitor, MonitorsSitemapExactMonitor, MonitorsPageSemanticMonitor, MonitorsExtractSemanticMonitor
]
