# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Dict, List, Union, Optional
from datetime import datetime
from typing_extensions import Literal, TypeAlias

from pydantic import Field as FieldInfo

from .._models import BaseModel

__all__ = [
    "MonitorListResponse",
    "Data",
    "DataMonitorsPageExactMonitor",
    "DataMonitorsPageExactMonitorChangeDetection",
    "DataMonitorsPageExactMonitorSchedule",
    "DataMonitorsPageExactMonitorTarget",
    "DataMonitorsPageExactMonitorWebhook",
    "DataMonitorsSitemapExactMonitor",
    "DataMonitorsSitemapExactMonitorChangeDetection",
    "DataMonitorsSitemapExactMonitorSchedule",
    "DataMonitorsSitemapExactMonitorTarget",
    "DataMonitorsSitemapExactMonitorWebhook",
    "DataMonitorsPageSemanticMonitor",
    "DataMonitorsPageSemanticMonitorChangeDetection",
    "DataMonitorsPageSemanticMonitorSchedule",
    "DataMonitorsPageSemanticMonitorTarget",
    "DataMonitorsPageSemanticMonitorWebhook",
    "DataMonitorsExtractSemanticMonitor",
    "DataMonitorsExtractSemanticMonitorChangeDetection",
    "DataMonitorsExtractSemanticMonitorSchedule",
    "DataMonitorsExtractSemanticMonitorTarget",
    "DataMonitorsExtractSemanticMonitorWebhook",
]


class DataMonitorsPageExactMonitorChangeDetection(BaseModel):
    """Detect exact changes.

    For page targets, this means visible text diffs. For sitemap targets, this means URL additions and removals.
    """

    type: Literal["exact"]


class DataMonitorsPageExactMonitorSchedule(BaseModel):
    """Run the monitor on a fixed interval defined by a frequency and a unit, e.g.

    every 6 hours or every 2 days. The total interval (frequency × unit) must be between 10 minutes and 1 year.
    """

    frequency: int
    """Number of units between runs.

    The resulting interval (frequency × unit) must be at least 10 minutes and at
    most 1 year (e.g. minimum 10 when unit is minutes; maximum 365 when unit is
    days).
    """

    type: Literal["interval"]

    unit: Literal["minutes", "hours", "days"]


class DataMonitorsPageExactMonitorTarget(BaseModel):
    type: Literal["page"]

    url: str

    normalize_whitespace: Optional[bool] = None
    """Normalize whitespace before comparing or analyzing text."""


class DataMonitorsPageExactMonitorWebhook(BaseModel):
    url: str
    """Webhook URL called when a change is detected."""

    secret: Optional[str] = None
    """Signing secret used to verify webhook authenticity.

    Each delivery includes an `X-Context-Signature: t=<unix>,v1=<hmac>` header,
    where the HMAC is SHA-256 over `"{t}.{rawRequestBody}"` keyed by this secret.
    Recompute it with a constant-time compare and reject stale timestamps to prevent
    replay. Generated by the API; cannot be set by clients.
    """


class DataMonitorsPageExactMonitor(BaseModel):
    """A page monitor using exact change detection."""

    id: str

    change_detection: DataMonitorsPageExactMonitorChangeDetection
    """Detect exact changes.

    For page targets, this means visible text diffs. For sitemap targets, this means
    URL additions and removals.
    """

    created_at: datetime

    name: str

    schedule: DataMonitorsPageExactMonitorSchedule
    """Run the monitor on a fixed interval defined by a frequency and a unit, e.g.

    every 6 hours or every 2 days. The total interval (frequency × unit) must be
    between 10 minutes and 1 year.
    """

    status: Literal["active", "paused", "failed"]

    target: DataMonitorsPageExactMonitorTarget

    updated_at: datetime

    last_change_at: Optional[datetime] = None

    last_run_at: Optional[datetime] = None

    tags: Optional[List[str]] = None
    """User-defined tags for grouping and filtering monitors and their changes."""

    webhook: Optional[DataMonitorsPageExactMonitorWebhook] = None


class DataMonitorsSitemapExactMonitorChangeDetection(BaseModel):
    """Detect exact changes.

    For page targets, this means visible text diffs. For sitemap targets, this means URL additions and removals.
    """

    type: Literal["exact"]


class DataMonitorsSitemapExactMonitorSchedule(BaseModel):
    """Run the monitor on a fixed interval defined by a frequency and a unit, e.g.

    every 6 hours or every 2 days. The total interval (frequency × unit) must be between 10 minutes and 1 year.
    """

    frequency: int
    """Number of units between runs.

    The resulting interval (frequency × unit) must be at least 10 minutes and at
    most 1 year (e.g. minimum 10 when unit is minutes; maximum 365 when unit is
    days).
    """

    type: Literal["interval"]

    unit: Literal["minutes", "hours", "days"]


class DataMonitorsSitemapExactMonitorTarget(BaseModel):
    type: Literal["sitemap"]

    url: str
    """Sitemap URL to monitor."""

    exclude: Optional[List[str]] = None
    """URL path patterns to exclude."""

    include: Optional[List[str]] = None
    """URL path patterns to include."""

    max_urls: Optional[int] = None


class DataMonitorsSitemapExactMonitorWebhook(BaseModel):
    url: str
    """Webhook URL called when a change is detected."""

    secret: Optional[str] = None
    """Signing secret used to verify webhook authenticity.

    Each delivery includes an `X-Context-Signature: t=<unix>,v1=<hmac>` header,
    where the HMAC is SHA-256 over `"{t}.{rawRequestBody}"` keyed by this secret.
    Recompute it with a constant-time compare and reject stale timestamps to prevent
    replay. Generated by the API; cannot be set by clients.
    """


class DataMonitorsSitemapExactMonitor(BaseModel):
    """A sitemap monitor using exact change detection."""

    id: str

    change_detection: DataMonitorsSitemapExactMonitorChangeDetection
    """Detect exact changes.

    For page targets, this means visible text diffs. For sitemap targets, this means
    URL additions and removals.
    """

    created_at: datetime

    name: str

    schedule: DataMonitorsSitemapExactMonitorSchedule
    """Run the monitor on a fixed interval defined by a frequency and a unit, e.g.

    every 6 hours or every 2 days. The total interval (frequency × unit) must be
    between 10 minutes and 1 year.
    """

    status: Literal["active", "paused", "failed"]

    target: DataMonitorsSitemapExactMonitorTarget

    updated_at: datetime

    last_change_at: Optional[datetime] = None

    last_run_at: Optional[datetime] = None

    tags: Optional[List[str]] = None
    """User-defined tags for grouping and filtering monitors and their changes."""

    webhook: Optional[DataMonitorsSitemapExactMonitorWebhook] = None


class DataMonitorsPageSemanticMonitorChangeDetection(BaseModel):
    """Detect meaning-level changes that match a natural language query."""

    query: str

    type: Literal["semantic"]

    confidence_threshold: Optional[float] = None


class DataMonitorsPageSemanticMonitorSchedule(BaseModel):
    """Run the monitor on a fixed interval defined by a frequency and a unit, e.g.

    every 6 hours or every 2 days. The total interval (frequency × unit) must be between 10 minutes and 1 year.
    """

    frequency: int
    """Number of units between runs.

    The resulting interval (frequency × unit) must be at least 10 minutes and at
    most 1 year (e.g. minimum 10 when unit is minutes; maximum 365 when unit is
    days).
    """

    type: Literal["interval"]

    unit: Literal["minutes", "hours", "days"]


class DataMonitorsPageSemanticMonitorTarget(BaseModel):
    type: Literal["page"]

    url: str

    normalize_whitespace: Optional[bool] = None
    """Normalize whitespace before comparing or analyzing text."""


class DataMonitorsPageSemanticMonitorWebhook(BaseModel):
    url: str
    """Webhook URL called when a change is detected."""

    secret: Optional[str] = None
    """Signing secret used to verify webhook authenticity.

    Each delivery includes an `X-Context-Signature: t=<unix>,v1=<hmac>` header,
    where the HMAC is SHA-256 over `"{t}.{rawRequestBody}"` keyed by this secret.
    Recompute it with a constant-time compare and reject stale timestamps to prevent
    replay. Generated by the API; cannot be set by clients.
    """


class DataMonitorsPageSemanticMonitor(BaseModel):
    """A page monitor using semantic change detection."""

    id: str

    change_detection: DataMonitorsPageSemanticMonitorChangeDetection
    """Detect meaning-level changes that match a natural language query."""

    created_at: datetime

    name: str

    schedule: DataMonitorsPageSemanticMonitorSchedule
    """Run the monitor on a fixed interval defined by a frequency and a unit, e.g.

    every 6 hours or every 2 days. The total interval (frequency × unit) must be
    between 10 minutes and 1 year.
    """

    status: Literal["active", "paused", "failed"]

    target: DataMonitorsPageSemanticMonitorTarget

    updated_at: datetime

    last_change_at: Optional[datetime] = None

    last_run_at: Optional[datetime] = None

    tags: Optional[List[str]] = None
    """User-defined tags for grouping and filtering monitors and their changes."""

    webhook: Optional[DataMonitorsPageSemanticMonitorWebhook] = None


class DataMonitorsExtractSemanticMonitorChangeDetection(BaseModel):
    """Detect meaning-level changes that match a natural language query."""

    query: str

    type: Literal["semantic"]

    confidence_threshold: Optional[float] = None


class DataMonitorsExtractSemanticMonitorSchedule(BaseModel):
    """Run the monitor on a fixed interval defined by a frequency and a unit, e.g.

    every 6 hours or every 2 days. The total interval (frequency × unit) must be between 10 minutes and 1 year.
    """

    frequency: int
    """Number of units between runs.

    The resulting interval (frequency × unit) must be at least 10 minutes and at
    most 1 year (e.g. minimum 10 when unit is minutes; maximum 365 when unit is
    days).
    """

    type: Literal["interval"]

    unit: Literal["minutes", "hours", "days"]


class DataMonitorsExtractSemanticMonitorTarget(BaseModel):
    type: Literal["extract"]

    url: str
    """Root URL to extract structured data from."""

    follow_subdomains: Optional[bool] = None

    instructions: Optional[str] = None
    """Optional natural-language instructions guiding what to extract."""

    max_depth: Optional[int] = None
    """Optional maximum link depth from the starting URL (0 = only the starting page)."""

    max_pages: Optional[int] = None
    """Maximum number of pages to analyze during extraction."""

    schema_: Optional[Dict[str, object]] = FieldInfo(alias="schema", default=None)
    """JSON Schema describing the structured data to extract and watch for changes.

    If omitted, a default summary + key-points schema is used.
    """


class DataMonitorsExtractSemanticMonitorWebhook(BaseModel):
    url: str
    """Webhook URL called when a change is detected."""

    secret: Optional[str] = None
    """Signing secret used to verify webhook authenticity.

    Each delivery includes an `X-Context-Signature: t=<unix>,v1=<hmac>` header,
    where the HMAC is SHA-256 over `"{t}.{rawRequestBody}"` keyed by this secret.
    Recompute it with a constant-time compare and reject stale timestamps to prevent
    replay. Generated by the API; cannot be set by clients.
    """


class DataMonitorsExtractSemanticMonitor(BaseModel):
    """An extract monitor using semantic change detection."""

    id: str

    change_detection: DataMonitorsExtractSemanticMonitorChangeDetection
    """Detect meaning-level changes that match a natural language query."""

    created_at: datetime

    name: str

    schedule: DataMonitorsExtractSemanticMonitorSchedule
    """Run the monitor on a fixed interval defined by a frequency and a unit, e.g.

    every 6 hours or every 2 days. The total interval (frequency × unit) must be
    between 10 minutes and 1 year.
    """

    status: Literal["active", "paused", "failed"]

    target: DataMonitorsExtractSemanticMonitorTarget

    updated_at: datetime

    last_change_at: Optional[datetime] = None

    last_run_at: Optional[datetime] = None

    tags: Optional[List[str]] = None
    """User-defined tags for grouping and filtering monitors and their changes."""

    webhook: Optional[DataMonitorsExtractSemanticMonitorWebhook] = None


Data: TypeAlias = Union[
    DataMonitorsPageExactMonitor,
    DataMonitorsSitemapExactMonitor,
    DataMonitorsPageSemanticMonitor,
    DataMonitorsExtractSemanticMonitor,
]


class MonitorListResponse(BaseModel):
    data: List[Data]

    has_more: bool

    next_cursor: Optional[str] = None
